// src/pages/HealthPrint.tsx
import { useEffect, useMemo } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Printer, ChevronLeft, HeartPulse, Syringe, Ruler } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useSession } from "@/hooks/useSession";
import { useChildren, useChildEvents, useVaccineStatus } from "@/hooks/usePregnancy";
import { useDailyDiary, rangeForLastNDays } from "@/hooks/useDailyDiary";
import { ageLabel } from "@/lib/dailyOptions";
import { ChildGrowthChart } from "@/components/daily/ChildGrowthChart";
import type { DailyChildProfile } from "@/types/daily";

export default function HealthPrint() {
    const { childId } = useParams<{ childId?: string }>();
    const navigate = useNavigate();
    const { user } = useSession();

    // If we got a childId via the URL, we'll look for it in the mother's list.
    // Otherwise the page prints the mother's own diary + all her children.
    const children = useChildren(user?.id);
    const child: DailyChildProfile | null = useMemo(() => {
        if (!childId) return null;
        return children.children.find((c) => c.id === childId) ?? null;
    }, [children.children, childId]);

    // Diary range — last 30 days
    const diaryRange = useMemo(() => rangeForLastNDays(30), []);
    const diary = useDailyDiary(user?.id, diaryRange);

    // Auto-fire print when the user lands on this page and clicks the button.
    // We don't auto-print — the user should see the preview first.

    const handlePrint = () => {
        window.print();
    };

    if (!user) return null;

    return (
        <div className="min-h-[100dvh] bg-white text-black">
            {/* Print-only header — page 1 top strip */}
            <div className="print-header hidden print:block px-8 pt-6 pb-3 border-b border-black">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <HeartPulse className="w-5 h-5" />
                        <p className="font-bold text-lg">HommieCare Health Record</p>
                    </div>
                    <p className="text-xs text-gray-600">
                        Printed {new Date().toLocaleDateString(undefined, {
                            day: "numeric", month: "long", year: "numeric",
                        })}
                    </p>
                </div>
                <div className="mt-2 text-xs text-gray-700">
                    <p><strong>Name:</strong> {user.display_name}</p>
                    {user.legal_name && <p><strong>Legal name:</strong> {user.legal_name}</p>}
                    {user.date_of_birth && (
                        <p>
                            <strong>DOB:</strong>{" "}
                            {new Date(user.date_of_birth).toLocaleDateString()}
                        </p>
                    )}
                    <p>
                        <strong>Generated by:</strong> {user.display_name}
                        {user.phone_number ? ` · ${user.phone_number}` : ""}
                    </p>
                </div>
            </div>

            {/* Screen-only chrome */}
            <div className="print:hidden max-w-3xl mx-auto px-4 py-6">
                <button
                    onClick={() => navigate(-1)}
                    className="inline-flex items-center gap-1 text-sm text-muted-foreground -ml-2 mb-4 h-11"
                >
                    <ChevronLeft className="w-4 h-4" /> Back
                </button>

                <div className="flex items-center justify-between gap-3 mb-5">
                    <div>
                        <h1 className="text-2xl font-black tracking-tight text-foreground">
                            Printable health record
                        </h1>
                        <p className="text-sm text-muted-foreground mt-1">
                            Vaccine schedule, growth, and recent health logs — ready to
                            share with a clinic.
                        </p>
                    </div>
                    <Button onClick={handlePrint} className="h-11 rounded-2xl shrink-0">
                        <Printer className="w-4 h-4 mr-1.5" /> Print / Save PDF
                    </Button>
                </div>
            </div>

            {/* Printable content */}
            <div className="print:px-8 print:py-4 max-w-3xl mx-auto px-4 pb-12 print:max-w-none print:mx-0">
                {/* ---------- MOTHER: Daily health summary (last 30 days) ---------- */}
                <section className="print-section mb-8">
                    <h2 className="text-lg font-bold mb-3 pb-1 border-b border-gray-300">
                        Recent health log — last 30 days
                    </h2>

                    {diary.isLoading ? (
                        <p className="text-sm text-gray-500">Loading…</p>
                    ) : diary.entries.length === 0 ? (
                        <p className="text-sm text-gray-500">
                            No entries logged in the last 30 days.
                        </p>
                    ) : (
                        <table className="w-full text-xs border-collapse">
                            <thead>
                                <tr className="border-b border-gray-300">
                                    <th className="text-left py-1.5 pr-2 font-semibold w-24">Date</th>
                                    <th className="text-left py-1.5 pr-2 font-semibold w-20">Type</th>
                                    <th className="text-left py-1.5 pr-2 font-semibold">
                                        Details
                                    </th>
                                    <th className="text-left py-1.5 font-semibold w-24">
                                        Severity
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {diary.entries.slice(0, 40).map((e) => (
                                    <tr key={e.id} className="border-b border-gray-100 align-top">
                                        <td className="py-1.5 pr-2 text-gray-700 whitespace-nowrap">
                                            {new Date(e.entry_date).toLocaleDateString(undefined, {
                                                day: "2-digit",
                                                month: "short",
                                            })}
                                        </td>
                                        <td className="py-1.5 pr-2 capitalize">{e.category}</td>
                                        <td className="py-1.5 pr-2">
                                            {e.title || e.notes || "—"}
                                            {e.medication_name && (
                                                <span className="text-gray-600">
                                                    {" "}
                                                    · {e.medication_name}
                                                    {e.medication_dose ? ` ${e.medication_dose}` : ""}
                                                </span>
                                            )}
                                        </td>
                                        <td className="py-1.5">
                                            {e.severity != null ? `${e.severity}/10` : "—"}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </section>

                {/* ---------- CHILDREN ---------- */}
                {children.children.length > 0 && (
                    <section className="print-section">
                        <h2 className="text-lg font-bold mb-3 pb-1 border-b border-gray-300">
                            Children ({children.children.length})
                        </h2>

                        <div className="space-y-8">
                            {children.children.map((c) => (
                                <ChildPrintBlock key={c.id} child={c} motherId={user.id} />
                            ))}
                        </div>
                    </section>
                )}

                {/* Footer */}
                <footer className="mt-8 pt-3 border-t border-gray-300 text-[10px] text-gray-500 text-center">
                    This record was generated by HommieCare. It is not an official medical
                    document. For clinical decisions, always consult a qualified
                    professional.
                </footer>
            </div>

            {/* Print styles injected locally */}
            <style>{`
                @media print {
                    @page {
                        size: A4;
                        margin: 12mm;
                    }
                    body {
                        background: white !important;
                        color: black !important;
                    }
                    .print-section {
                        break-inside: avoid;
                    }
                    .print-page-break {
                        break-before: page;
                    }
                    table {
                        font-size: 10pt !important;
                    }
                }
            `}</style>
        </div>
    );
}

// ============================================================
// One child — vaccine table + growth chart + recent events
// ============================================================
function ChildPrintBlock({
    child,
    motherId,
}: {
    child: DailyChildProfile;
    motherId: string;
}) {
    const events = useChildEvents(child.id, motherId);
    const schedule = useVaccineStatus(child, events.events);

    const done = schedule.filter((v) => v.status === "done").length;
    const overdue = schedule.filter((v) => v.status === "overdue").length;

    return (
        <div className="print-page-break">
            {/* Child header */}
            <div className="flex items-start justify-between gap-3 mb-3 pb-2 border-b border-gray-200">
                <div>
                    <h3 className="text-base font-bold">
                        {child.full_name}
                        {child.nickname ? ` (${child.nickname})` : ""}
                    </h3>
                    <p className="text-xs text-gray-600 mt-0.5">
                        {ageLabel(child.date_of_birth)} old · born{" "}
                        {new Date(child.date_of_birth).toLocaleDateString(undefined, {
                            day: "numeric", month: "long", year: "numeric",
                        })}
                        {child.sex !== "unknown" && ` · ${child.sex}`}
                    </p>
                    {child.primary_facility && (
                        <p className="text-xs text-gray-600">
                            Clinic: {child.primary_facility}
                            {child.primary_facility_phone
                                ? ` · ${child.primary_facility_phone}`
                                : ""}
                        </p>
                    )}
                </div>
                <div className="text-right text-xs shrink-0">
                    <p className="font-semibold">
                        {done} / {schedule.length} vaccines
                    </p>
                    {overdue > 0 && (
                        <p className="text-red-600 font-semibold">
                            {overdue} overdue
                        </p>
                    )}
                </div>
            </div>

            {/* Vaccine table */}
            <div className="mb-4">
                <div className="flex items-center gap-1.5 mb-2">
                    <Syringe className="w-3.5 h-3.5" />
                    <h4 className="text-sm font-semibold">Immunization record</h4>
                </div>
                <table className="w-full text-xs border-collapse">
                    <thead>
                        <tr className="border-b border-gray-300">
                            <th className="text-left py-1 pr-2 font-semibold">Vaccine</th>
                            <th className="text-left py-1 pr-2 font-semibold w-24">Age due</th>
                            <th className="text-left py-1 pr-2 font-semibold w-24">Status</th>
                            <th className="text-left py-1 font-semibold w-24">Given</th>
                        </tr>
                    </thead>
                    <tbody>
                        {schedule.map((v) => (
                            <tr key={v.key} className="border-b border-gray-100">
                                <td className="py-1 pr-2">
                                    {v.label}
                                    {v.dose > 0 && (
                                        <span className="text-gray-500"> · dose {v.dose}</span>
                                    )}
                                </td>
                                <td className="py-1 pr-2 text-gray-700">{v.age_label}</td>
                                <td className="py-1 pr-2">
                                    {v.status === "done" && (
                                        <span className="text-green-700">✓ Done</span>
                                    )}
                                    {v.status === "due" && (
                                        <span className="text-blue-700">Due now</span>
                                    )}
                                    {v.status === "overdue" && (
                                        <span className="text-red-600 font-semibold">Overdue</span>
                                    )}
                                    {v.status === "upcoming" && (
                                        <span className="text-gray-500">Upcoming</span>
                                    )}
                                </td>
                                <td className="py-1 text-gray-700">
                                    {v.done_on
                                        ? new Date(v.done_on).toLocaleDateString(undefined, {
                                            day: "2-digit",
                                            month: "short",
                                            year: "2-digit",
                                        })
                                        : "—"}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Growth chart */}
            <div className="mb-4">
                <div className="flex items-center gap-1.5 mb-2">
                    <Ruler className="w-3.5 h-3.5" />
                    <h4 className="text-sm font-semibold">Growth</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 print:grid-cols-2">
                    <ChildGrowthChart events={events.events} metric="weight" />
                    <ChildGrowthChart events={events.events} metric="height" />
                </div>
            </div>

            {/* Recent events (last 10) */}
            {events.events.length > 0 && (
                <div>
                    <h4 className="text-sm font-semibold mb-2">
                        Recent events ({events.events.length})
                    </h4>
                    <table className="w-full text-xs border-collapse">
                        <thead>
                            <tr className="border-b border-gray-300">
                                <th className="text-left py-1 pr-2 font-semibold w-24">Date</th>
                                <th className="text-left py-1 pr-2 font-semibold w-28">Type</th>
                                <th className="text-left py-1 font-semibold">Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            {events.events.slice(0, 10).map((e) => (
                                <tr key={e.id} className="border-b border-gray-100 align-top">
                                    <td className="py-1 pr-2 text-gray-700 whitespace-nowrap">
                                        {new Date(e.entry_date).toLocaleDateString(undefined, {
                                            day: "2-digit",
                                            month: "short",
                                        })}
                                    </td>
                                    <td className="py-1 pr-2 capitalize">
                                        {e.event_type.replace(/_/g, " ")}
                                    </td>
                                    <td className="py-1">
                                        {[
                                            e.visit_reason,
                                            e.illness_type,
                                            e.vaccine_key,
                                            e.milestone_key,
                                            e.notes,
                                        ]
                                            .filter(Boolean)
                                            .join(" · ") || "—"}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}